config/routes.rb
Rails.application.routes.draw do

  resources :projects do
    resources :tasks
  end

  root "projects#index"

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tasks
  
  validates :title, presence: true

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project

  validates :title, presence: true

  scope :pending,   -> { where(completed: false) }
  scope :completed, -> { where(completed: true)  }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_project, only: [:edit, :show, :update, :destroy]

  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to @project, notice: "Project created."
    else
      render :new
    end
  end

  def edit
  end

  def show
    @pending_tasks   = @project.tasks.pending
    @completed_tasks = @project.tasks.completed
  end

  def update
    if @project.update_attributes(project_params)
      redirect_to @project, notice: "Project updated"
    else
      render :edit
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path, notice: "Project deleted"
  end

  private

  def project_params
    params.require(:project).permit(:title, :description)
  end

  def find_project
    @project = Project.find(params[:id])
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :find_project

  def create
    @task = @project.tasks.new(task_params)
    if @task.save
      render json: {status: "success", 
                    title: @task.title,
                    url: project_task_path(@project, @task)}
    else
      render json: {status: "failure", errors: @task.errors.full_messages}
    end
  end

  def update
    @task = Task.find(params[:id])
    if @task.update_attributes(task_params)
      render json: {status: "success"}
    else
      render json: {status: "failure"}
    end
  end

  private

  def task_params
    params.require(:task).permit(:title, :completed)
  end

  def find_project
    @project = Project.find params[:project_id]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title PmInClass
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .container
      .nav.nav-bar= link_to "Home", root_path
      = yield

app/views/projects/_form.html.haml
= simple_form_for @project, html: {class: "form-horizontal"} do |f|
  = f.input :title
  = f.input :description
  = f.submit "Save", class: "btn btn-primary"

app/views/projects/_project.html.haml
%h2= link_to project.title, project
%p= project.description
%hr

app/views/projects/edit.html.haml
%h1 Edit Project

= render "form"

app/views/projects/index.html.haml
%h1 Welcome to my PM Tool

= link_to "New Project", new_project_path, class: "btn btn-primary"
= render @projects

app/views/projects/new.html.haml
%h1 Create New Project

= render "form"

app/views/projects/show.html.haml
%h1= @project.title
%p= @project.description

= link_to "Edit", edit_project_path(@project), class: "btn btn-info"
|
= link_to "Delete", @project, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger"
%hr

%script#task-template{type: "x-tmpl-mustache"}
  .well.draggable{data: {url: "{{url}}"}}
    .glyphicon.glyphicon-th
    {{title}}

#task-errors
= simple_form_for [@project, Task.new] do |f|
  = f.input :title
  = f.submit "Save Task", class: "btn btn-primary"

.row
  .col-sm-6
    Pending Tasks
    .well
      #pending-tasks.droppable
        - @pending_tasks.each do |task|
          .well.draggable{data: {url: project_task_path(@project, task)}}
            .glyphicon.glyphicon-th
            = task.title
  .col-sm-6
    Completed Tasks
    .well
      #completed-tasks.droppable
        - @completed_tasks.each do |task|
          .well.draggable{data: {url: project_task_path(@project, task)}}
            .glyphicon.glyphicon-th
            = task.title